### ISSUE TITLE
Issues with the multi-view RGB example

### ISSUE THREAD

**Issue by fcole** [martinResearch/DEODR#21]
Thanks for the nicely packaged code! I have two questions about the multi-view RGB example:

1. two of the three input images have extensions ".JPG" instead of ".jpg" and aren't captured by the python glob.glob call on my Linux machine. Renaming the files to ".jpg" seems to fix the example.

2. When I run the example, I get an energy profile like this (image attached):
<img width="1265" alt="Screen Shot 2020-05-02 at 11 56 20 PM" src="https://user-images.githubusercontent.com/508398/80898415-241aa180-8cd1-11ea-84a4-9996d8292963.png">

Where the minimum is reached about midway through the run and then the energy appears to increase again. Is this the expected result?

**Comment by martinResearch** [comment]
Hi, thank you for spotting the problem of capital letter extensions on linux. 

Regarding the convergence of the multiview fitting, I am getting slightly different results and I had to increase the number of iteration to 500 to see  a significant increase of the energy : 
![image](https://user-images.githubusercontent.com/18285382/81070324-f99c3480-8eda-11ea-91ce-5488d504dd9a.png)

Indeed it is a bit surprising to the energy going up again, which is opposite to what we aim for. I did not spend much time investigating why this is the case. It would be good to rule out a errors in the gradient computation by comparing with the one obtained with finite differentiation, which I have done on other data but I could easily do for that for this example too. It could be that self intersection are starting to cause problem as the gradient becomes incorrect in case of visible aliasing at self intersections (which seem to appear at some point). 

Also it looks like the vertices start oscillating a lot around a mean position and maybe we are entering some kind of resonance mode of the "as rigid as possible" term, because the the step size is too large with respect to the curvature. This could probably be mitigated by using an adaptive step size, a line search at each iteration , or using a pseudo newton method like BFGS (which could also speedup the convergence).

**Comment by martinResearch** [comment]
I increased the damping factor and managed to get much more stable results. 
Making the edge anti-aliazing rasterization more robust in case of near vertical edges (to avoid overflow in division by very small values ) may also have played a role. 
Result after https://github.com/martinResearch/DEODR/pull/68
![image](https://user-images.githubusercontent.com/18285382/101994236-ca437680-3cb8-11eb-962e-c1e678583b20.png)
