### ISSUE TITLE
Questions about examples.

### ISSUE THREAD

**Issue by dihuangdh** [martinResearch/DEODR#25]
Hi, @martinResearch 

It's me again  : )

1. How to set `max_depth` ? If I want to use real depth image, should I use real depth limitation?

2. How to set `depth_scale` ? Again, if I want to use real depth image from rgbd camera, should I set it to 1?

3. In multi-view example ... I thought there should be more than one camera. However, you only create 1 camera, but use `euler` and `translation` to change view. Why not create some cameras and use different `extrinsic` parameters?

**Comment by martinResearch** [comment]
1. At the moment  `MeshDepthFitter` assumes that the object you are fitting to is closer than the rest of the scene. If that the case you should `set_depth_scale` with `max_depth` chosen between  the maximum depth of the object you are fitting and the minimum depth of the backround (I may example I actually use a smaller depth to remove the arm). Thanks to the max_depth clipping I don't need to model the background depth. However in case we have a background depth  I could add the possibility to provide a background depth to the fitter.

2. `depth_scale` is a factor I tuned by trial and error because my hand mesh units and size does not correspond to the size of the real hand in the range image I am using and because I rescaled the values of the input depth in my example. You can set it to 1 if the vertices on the hand mesh you are using use the same unit as your depth image and if your mesh hand size matches well enough the one in you real data. Alternatively we could simply rescale the mesh vertices. I will try to work on a cleaner example where only the mesh vertices get rescaled.

3. My use of the term "multiview" in the name of the example file `rgb_multiview_hand.py` is slightly wrong here, I am actually rotating the mesh in the three images, keeping the camera and light fixed. So it is more "multiframe" than "multiview" (hence the name of the underlying class `MeshRGBFitterWithPoseMultiFrame`). I should rename the file to `rgb_mutliframes_hand.py` for example. I could add an actual "multiview" example, with precalibrated cameras with different intrinsics and extrinsics

**Comment by dihuangdh** [comment]
It's clear. Thanks a lot.
