### ISSUE TITLE
Camera and coordinate system convention

### ISSUE THREAD

**Issue by chongli-uw** [martinResearch/DEODR#77]
Hi Martin, 
  Thanks for the great work! I am confused about the coordinate system convention (right handed vs left handed) and the default camera direction (camera pointing to Z+ or Z- axis) adopted in DEODR. Basically I loaded the same [mesh](https://github.com/martinResearch/DEODR/blob/345141caba121d9688489ee96a836833123e1a74/deodr/examples/depth_image_hand_fitting.py#L45) and set the same [object pose](https://github.com/martinResearch/DEODR/blob/345141caba121d9688489ee96a836833123e1a74/deodr/examples/depth_image_hand_fitting.py#L48) and [camera pose](https://github.com/martinResearch/DEODR/blob/345141caba121d9688489ee96a836833123e1a74/deodr/tensorflow/mesh_fitter_tensorflow.py#L99) as defined in the [depth fitting example](https://github.com/martinResearch/DEODR/blob/master/deodr/examples/depth_image_hand_fitting.py) in Maya (and OpenGL),  but I could not get the same rendered image as in DEODR (camera not pointing towards the mesh). 

  More specifically, 
1. why do we rotation the camera by 180 degree around the X-axis ([this line](https://github.com/martinResearch/DEODR/blob/345141caba121d9688489ee96a836833123e1a74/deodr/tensorflow/mesh_fitter_tensorflow.py#L99)) ?  
2. I am confused about the dot product between the translation of the camera and the rotation ([this line](https://github.com/martinResearch/DEODR/blob/345141caba121d9688489ee96a836833123e1a74/deodr/tensorflow/mesh_fitter_tensorflow.py#L100))

These are trivial questions but I would truly appreciate some clarification. Thanks for your kind help!

**Comment by martinResearch** [comment]
Hi Chong,
I use the same convention as opencv described here https://docs.opencv.org/4.5.1/d9/d0c/group__calib3d.html
i.e.
![image](https://user-images.githubusercontent.com/18285382/103457252-6d564180-4cf5-11eb-8cc6-e34e252c628f.png)
regarding the choice of the rotation and translation part of the extrinsic parameters (3x4 matrix that should not be interpreted as the camera pose but its inverse) I have made in the MeshDepthFitter class, it is somewhat arbitrary. I chose the rotation and translation so that the rendered mesh appears in a similar position and orientation to when opened with meshlab. 
The translation here https://github.com/martinResearch/DEODR/blob/345141caba121d9688489ee96a836833123e1a74/deodr/mesh_fitter.py#L49
is also somewhat arbitrary. It would be much cleaner to allow the user to provide the full camera as an input to the MeshDepthFitter constructor.
I do not know how cameras are parameterized in maya.  You may need to get the camera pose using the  `camera_to_world_mtx_4x4` method

**Comment by chongli-uw** [comment]
Thanks Martin! For those Maya users, the Maya camera parameter can be converted to OpenCV convention as used in DEODR using this package https://github.com/chloelle/MayaCamera.
